# Generated by Django 3.2.12 on 2022-04-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communnity',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Communities'},
        ),
    ]
