# Generated by Django 3.2.12 on 2022-04-26 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='communnity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='communnity.communnity'),
        ),
    ]
