# Generated by Django 3.2.12 on 2022-04-26 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communnity', '0002_alter_team_communnity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='communnity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communnity.communnity'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
