# Generated by Django 3.2.12 on 2022-05-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0004_auto_20220426_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('m', 'member'), ('l', 'leader')], default='member', max_length=100),
        ),
    ]
