# Generated by Django 3.2.12 on 2022-05-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0005_alter_team_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communnity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
