# Generated by Django 3.2.12 on 2022-05-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='codeforces_account',
            new_name='codeforces',
        ),
    ]
