# Generated by Django 3.2.12 on 2022-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.URLField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
