# Generated by Django 3.2.12 on 2022-04-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codeforces_account',
            field=models.CharField(default=22, max_length=200),
            preserve_default=False,
        ),
    ]
