# Generated by Django 3.2.12 on 2022-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220329_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cv',
            field=models.FileField(default='', upload_to='decomends'),
        ),
    ]
