# Generated by Django 3.2.12 on 2022-04-14 21:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220411_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
