# Generated by Django 3.2.12 on 2022-05-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelfeedback',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='level.level'),
        ),
        migrations.AlterField(
            model_name='levelteam',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='level.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='level.level'),
        ),
        migrations.AlterField(
            model_name='teamfeedback',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamfeedback', to='level.level'),
        ),
    ]
