# Generated by Django 3.2.12 on 2022-05-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_remove_round_bio'),
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='disc',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('round', 'name')},
        ),
    ]
