# Generated by Django 3.2.12 on 2022-06-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelteam',
            options={'verbose_name': 'LevelTeam', 'verbose_name_plural': 'LevelTeams'},
        ),
        migrations.AddField(
            model_name='levelteam',
            name='role',
            field=models.CharField(choices=[('instructor', 'instructor'), ('mentor', 'mentor')], default='instructor', max_length=200),
        ),
    ]
