# Generated by Django 3.2.12 on 2022-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_auto_20220602_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelteam',
            name='role',
            field=models.CharField(choices=[('instructor', 'instructor'), ('mentor', 'mentor')], default='mentor', max_length=200),
        ),
    ]
