# Generated by Django 3.2.12 on 2022-06-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='level.level'),
        ),
    ]
