# Generated by Django 3.2.12 on 2022-06-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0006_levelfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelfeedback',
            options={'verbose_name': 'LevelFeedback', 'verbose_name_plural': 'LevelFeedbacks'},
        ),
    ]
