# Generated by Django 3.2.12 on 2022-06-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0007_alter_levelfeedback_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelfeedback',
            old_name='disc',
            new_name='feedback',
        ),
    ]
