# Generated by Django 3.2.12 on 2022-06-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0008_rename_disc_levelfeedback_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelfeedback',
            old_name='user',
            new_name='student',
        ),
    ]
