# Generated by Django 3.2.12 on 2022-06-12 12:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0010_alter_levelfeedback_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTeamFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamfeedback', to='level.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback', to='level.student')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_feedback', to='level.levelteam')),
            ],
        ),
    ]
