# Generated by Django 3.2.12 on 2022-06-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0011_levelteamfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelteamfeedback',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_feedbacks', to='level.levelteam'),
        ),
    ]
