# Generated by Django 3.2.12 on 2022-06-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0013_alter_levelteamfeedback_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelteamfeedback',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levl_feedbacks', to='level.level'),
        ),
        migrations.AlterField(
            model_name='levelteamfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedbacks', to='level.student'),
        ),
        migrations.AlterField(
            model_name='levelteamfeedback',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='level.levelteam'),
        ),
    ]
