# Generated by Django 3.2.12 on 2022-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
