# Generated by Django 3.2.12 on 2022-08-03 16:39

from django.db import migrations, models
import modules.community.models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_team_facebook_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to=modules.community.models.user_directory_path),
        ),
    ]
