# Generated by Django 3.2.12 on 2022-04-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0002_alter_communnity_options'),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='communnity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='communnity.communnity'),
        ),
    ]
