# Generated by Django 3.2.12 on 2022-05-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='bio',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
