# Generated by Django 3.2.12 on 2022-05-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_round_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='bio',
        ),
    ]
