# Generated by Django 3.2.12 on 2022-04-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_rename_communnity_id_round_communnity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundfeedback',
            old_name='round_id',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='roundfeedback',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='roundteam',
            old_name='round_id',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='roundteam',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='round_id',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
    ]
