# Generated by Django 3.2.12 on 2022-05-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_round_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
