# Generated by Django 3.2.12 on 2022-04-24 11:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('round', '0002_member_roundteam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Student',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.CreateModel(
            name='TeamFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('disc', models.TextField()),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.roundteam')),
            ],
        ),
        migrations.CreateModel(
            name='RoundFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.round')),
            ],
        ),
    ]
