# Generated by Django 3.2.12 on 2022-04-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_auto_20220424_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfeedback',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='round.student'),
            preserve_default=False,
        ),
    ]
