# Generated by Django 3.2.12 on 2022-05-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_remove_round_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
