# Generated by Django 3.2.12 on 2022-05-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_alter_round_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='slug',
        ),
    ]
