# Generated by Django 3.2.12 on 2022-04-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0004_alter_roundteam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundteam',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roundteam', to='round.round'),
        ),
    ]
