# Generated by Django 3.2.12 on 2022-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0004_remove_round_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
