# Generated by Django 3.2.12 on 2022-04-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0006_alter_roundteam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roundstudent', to='round.round'),
        ),
    ]
