# Generated by Django 3.2.12 on 2022-04-30 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('round', '0007_alter_student_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamfeedback',
            name='student',
        ),
        migrations.AddField(
            model_name='teamfeedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userteamfeedback', to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamfeedback',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamfeedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
