# Generated by Django 3.2.12 on 2022-04-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0009_teamfeedback_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamfeedback',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.round'),
        ),
    ]
